services:
  db:
    image: postgres:15
    container_name: sporty_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sporty
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: ./api
    container_name: sporty_api
    ports:
      - "8000:8000"
    depends_on:
      - db

  bot:
    build: ./bot
    container_name: sporty_bot
    depends_on:
      - api

volumes:
  postgres_data:
